# Generated by Django 5.0.7 on 2025-10-27 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_sketch_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='sketch',
            name='audio_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sketch',
            name='audio_summary',
            field=models.FileField(blank=True, null=True, upload_to='audio_summaries/'),
        ),
        migrations.AddField(
            model_name='sketch',
            name='ocr_explanation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
